# Generated by Django 5.0 on 2023-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year_released', models.IntegerField()),
                ('company', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('rls', 'Released'), ('nrls', 'Not Released')], max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Game_PC',
        ),
    ]
