# Generated by Django 5.0 on 2023-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_delete_game_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('not Released', 'Not Released')], max_length=12),
        ),
    ]
